title: "پروفایل محسن آقاجانی"
email: "aghajani69m@gmail.com"
description: "رزومه و پروفایل محسن آقاجانی"
baseurl: "https://github.com/aghajani69m"
url: "https://aghajani69m.github.io"
theme: jekyll-theme-cayman  
